### ISSUE TITLE
Tim's Kicad todo list

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#19004]
# Changes to KiCad I wish to do
## Phase 1 tasks
* [ ]  Fix running UCRT64 KiCad; it fails to open GUI program. Traced problem to PCM
* [ ] Get MINGW32 and CLANG32 kicad packages to build

## Phase 2 tasks
* [ ] Create simple kicad run-time check list
* [ ]  Create kicad package(s) for version 6.x

# Items put on hold because the idea of moving data libs to /usr/share has had objections raised to it
-  Move KiCad Library to MSys2 Repo [MSYS2 PR 4165](https://github.com/msys2/MSYS2-packages/pull/4165)
- Edit main kicad package to use the KiCad Library in MSys2 Repo
- Move kicad-docs to MSys2 repo
- Edit main kicad package to use the KiCad Docs in MSys2 Repo

Tim S.

**Comment by stahta01** [comment]
simple kicad run-time check list

- Kicad program open for each mingw enviroment
- Kicad splash screen is shown
- Kicad program open up GUI
- Help -> About Kicad shows the correct version number
- Preferences -> Configure Paths shows the correct information
- File -> Open Demo project works
- File -> Close project works
- File -> new project from template works
- File -> Quit works

**Comment by stahta01** [comment]
Due to the feedback, I have decided no one wants the package fixed.
