### ISSUE TITLE
Updating Out of Date MINGW-packages

### ISSUE THREAD

**Issue by hiroakit** [msys2/MINGW-packages#6342]
## Overview

In Apr. 1th, 2020 GMT,
[Out of Date MINGW-packages](https://packages.msys2.org/outofdate) is below:
- [x] mingw-w64-python-oslotest (#6364)
- [x] mingw-w64-gtk3 (#6352, a2f59cc, 62b98e4)
- [x] mingw-w64-mesa (#6349)
- [ ] mingw-w64-python-xpra
- [x] mingw-w64-pyqt5 (20f3f09)
- [x] mingw-w64-x265 (#6343)
- [ ] mingw-w64-python-httplib2
- [ ] mingw-w64-python-cryptography
- [ ] mingw-w64-python-django
- [ ] mingw-w64-python-zeroconf
- [ ] mingw-w64-python-pep517
- [x] mingw-w64-re2 (#6361)
- [x] mingw-w64-librsvg (#6345)
- [ ] mingw-w64-python-oslo-context
- [ ] mingw-w64-python-stestr
- [x] mingw-w64-python-zope.interface (15cb482)
- [ ] mingw-w64-python-hacking
- [x] mingw-w64-lib3mf (#6398)
- [ ] mingw-w64-poppler (#6344)
- [ ] mingw-w64-python-pyperclip
- [ ] mingw-w64-waf
- [ ] mingw-w64-python-alembic
- [x] mingw-w64-python-yaml (#6365)
- [ ] mingw-w64-python-prompt_toolkit
- [ ] mingw-w64-verilator
- [x] mingw-w64-python-cliff (#6356)
- [ ] mingw-w64-dnscrypt-proxy
- [ ] mingw-w64-soci
- [ ] mingw-w64-graphviz
- [ ] mingw-w64-farstream
- [ ] mingw-w64-perl
- [ ] mingw-w64-ghostscript
- [ ] mingw-w64-jbig2dec
- [ ] mingw-w64-libelf
- [ ] mingw-w64-cogl
- [ ] mingw-w64-git-lfs
- [ ] mingw-w64-totem-pl-parser
- [ ] mingw-w64-libgphoto2
- [ ] mingw-w64-libnotify
- [ ] mingw-w64-libgusb
- [ ] mingw-w64-python-psutil
- [ ] mingw-w64-python-pysocks
- [ ] mingw-w64-scummvm
- [ ] mingw-w64-pango
- [ ] mingw-w64-lsqlite3
- [ ] mingw-w64-lua-luarocks
- [ ] mingw-w64-meanwhile
- [ ] mingw-w64-libmariadbclient
- [ ] mingw-w64-file
- [ ] mingw-w64-libmfx
- [ ] mingw-w64-fontconfig
- [ ] mingw-w64-libvirt
- [ ] mingw-w64-bullet
- [ ] mingw-w64-apr
- [ ] mingw-w64-osgearth
- [ ] mingw-w64-gts
- [ ] mingw-w64-mlpack
- [ ] mingw-w64-lapack
- [ ] mingw-w64-gettext
- [ ] mingw-w64-diffutils
- [ ] mingw-w64-ldns
- [ ] mingw-w64-libmaxminddb
- [ ] mingw-w64-cereal
- [ ] mingw-w64-libressl
- [ ] mingw-w64-aspell
- [ ] mingw-w64-cairo
- [ ] mingw-w64-uasm
- [ ] mingw-w64-seexpr
- [ ] mingw-w64-gnome-latex
- [ ] mingw-w64-adns
- [ ] mingw-w64-dcraw
- [ ] mingw-w64-png2ico
- [x] mingw-w64-openssl (2ad58ce) 
- [x] mingw-w64-qt-creator (4f08673) 
- [x] mingw-w64-qbittorrent (#6338)
- [x] mingw-w64-armadillo (caa77c5)
- [x] mingw-w64-atk (b613803)
- [x] mingw-w64-ccache (2ec8ea5)
- [x] mingw-w64-eog (dde8012)
- [x] mingw-w64-freetds (7032c9c)
- [x] mingw-w64-graphite2 (1539fb5)
- [x] mingw-w64-qxmpp (0720fef)
- [x] mingw-w64-ruby (d615b81)
- [x] mingw-w64-sip (122b3ca)
- [x] mingw-w64-vapoursynth (c4a2b58)
- [x] mingw-w64-imagemagick (#6339, ef23a3d, #6366)

To make it easier to participate, 
listed packages that need to build.

**Comment by lazka** [comment]
@hiroakit thanks for helping out! Since there hasn't been any change in a while and this gets outdated very quickly I'm closing this.

We have https://packages.msys2.org/outofdate anyway
